[package]
name = "platform-backend"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
platform-core = { path = "../platform-core" }
rama = { version = "0.3.0-alpha.4", features = ["http", "http-full"] }
tokio = { version = "1", features = ["full"] }
async-stream = "0.3"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
ring = "0.17.14"
hex = "0.4"
chrono = "0.4"
sea-orm = { version = "1.1", features = ["sqlx-sqlite", "runtime-tokio-rustls", "macros"] }
sea-orm-migration = { version = "1.1.0", features = ["sqlx-sqlite", "runtime-tokio-rustls"] }
migration = { path = "./migration" }
serde_urlencoded = "0.7"
uuid = { version = "1", features = ["v4"] }
dotenvy = "0.15"
regex = "1.12.3"
